project:
  type: website
  output-dir: docs

website:
  title: "Dr. Furtado"
  reader-mode: true
  
  navbar:
    search: true
    background: light
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Teaching"
        menu: 
          - text: "KIN 610"
            icon: "graph-up"
            href: https://drfurtado.github.io/kin610/
          - text: "KIN 377"
            icon: "intersect"
            href: courses/377/index.qmd
          - text: "KIN 477"
            icon: "book"
            href: courses/477/index.qmd
      - text: "Blog"
        href: blog/index.qmd
  
    right:
      - icon: twitter
        href: https://twitter.com/ofurtado
      - icon: github
        href: https://github.com/drfurtado

  sidebar:
    - id: 377-intro
      collapse-level: 1
      style: "docked"
      contents:
        - text: "KIN 377 Intro"
          href: courses/377/index.qmd
        - text: "Syllabus"
          href: courses/377/syllabus.qmd
          
    - id: 477-intro
      collapse-level: 1
      style: "docked"
      contents:
        - text: "KIN 477 Intro"
          href: courses/477/index.qmd
        - text: "Syllabus"
          href: courses/477/syllabus.qmd
        - section: "Assignments"
          contents: 
            - text: "Discussion 1"
              href: courses/477/assignments/disc1.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual