project:
  type: website
  output-dir: _site

website:
  title: "Dr. Furtado"
  reader-mode: true
  
  navbar:
    search: true
    background: light
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Teaching"
        menu: 
          - text: "KIN 610"
            icon: "book"
            href: courses/610/index.qmd
  
    right:
      - icon: twitter
        href: https://twitter.com/ofurtado
      - icon: github
        href: https://github.com/drfurtado

  sidebar:
    - id: 610-intro
      collapse-level: 1
      style: "docked"
      contents:
        - text: "Intro"
          href: courses/610/index.qmd
        - text: "Syllabus"
          href: courses/610/syllabus.qmd
        - section: "Lessons"
          contents:
            - text: "Multiple Regression"
              href: courses/610/les-regression-m.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual