project:
  type: website
  output-dir: docs

website:
  title: "Dr. Furtado"
  reader-mode: true
  
  navbar:
    search: true
    background: light
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Teaching"
        menu: 
          - text: "KIN 610"
            icon: "bug"
            href: courses/610/index.qmd
          - text: "KIN 377"
            icon: "bug"
            href: courses/377/index.qmd
      - text: "Blog"
        href: blog/index.qmd
  
    right:
      - icon: twitter
        href: https://twitter.com/ofurtado
      - icon: github
        href: https://github.com/drfurtado

  sidebar:
    - id: 610-intro
      collapse-level: 1
      style: "docked"
      contents:
        - text: "KIN 610 Intro"
          href: courses/610/index.qmd
        - text: "Syllabus"
          href: courses/610/syllabus.qmd
        - text: "Sequence"
          href: courses/610/sequence.qmd
        - section: "Lessons"
          contents:
            - text: "Lesson 01"
              href: courses/610/les01.qmd
            - text: "Lesson 02"
              href: courses/610/les02.qmd
            - text: "Lesson 03"
              href: courses/610/les03.qmd
            - text: "Lesson 04"
              href: courses/610/les04.qmd
            - text: "Lesson 05"
              href: courses/610/les05.qmd
    - id: 377-intro
      collapse-level: 1
      style: "docked"
      contents:
        - text: "KIN 377 Intro"
          href: courses/377/index.qmd
        - text: "Syllabus"
          href: courses/377/syllabus.qmd
        - section: "Modules"
          contents:
            - text: "Module 01"
              href: courses/377/mod01.qmd
            - text: "Module 02"
              href: courses/377/mod02.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual