project:
  type: website

website:
  title: "Dr. Furtado"
  navbar:
    search: true
    background: light
    collapse-below: lg
    left:
      - text: "Home"
        file: index.qmd
        sidebar: teaching

    sidebar:
      - id: teaching
        title: "Teaching"
        background: light
        collapse-level: 2
        contents: 

    right:
      - icon: twitter
        href: https://twitter.com/ofurtado
      - icon: github
        href: https://github.com/drfurtado
    
    
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual